version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "1080:80"
    env_file:
      - ./.env.prod
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    expose:
      - 5432

  pgadmin4:
    image: dpage/pgadmin4:5.5
    restart: unless-stopped
    env_file:
      - ./.env.prod
    expose:
      - 80

  backupdb:
    build:
      context: ./backupdb
      dockerfile: Dockerfile
    restart: unless-stopped  
    env_file:
      - ./.env.prod.db
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
  