"""
Django settings for semprini project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "semprini",
    "devcast",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    # puput's search route records hits via this app's Query model. Without it
    # installed, Django binds those models to wagtailcore instead and the
    # tables are never created, so blog search 500s.
    "wagtail.contrib.search_promotions",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtailmarkdown",
    "wagtail",
    "modelcluster",
    "taggit",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.postgres",
    'wagtail.contrib.routable_page',
    'django_social_share',
    'puput',
    'colorful',
    'mozilla_django_oidc',
    'feedback',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'oidc_backend.SempriniOIDCBackend',
]

# --- Keycloak OIDC (mozilla-django-oidc) ---
# Endpoints are fixed to the semprini Keycloak realm; secrets come from env.
_KC = 'https://auth.semprini.me/realms/semprini/protocol/openid-connect'
OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID', '')
OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET', '')
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_OP_AUTHORIZATION_ENDPOINT = f'{_KC}/auth'
OIDC_OP_TOKEN_ENDPOINT = f'{_KC}/token'
OIDC_OP_USER_ENDPOINT = f'{_KC}/userinfo'
OIDC_OP_JWKS_ENDPOINT = f'{_KC}/certs'
OIDC_RP_SCOPES = 'openid email profile'

# Keycloak brokers the social logins (GitHub, and Google/Microsoft once their
# credentials are filled in), so it is the way visitors sign in: send anything
# that asks for a login - @login_required, Wagtail's private pages - straight
# there rather than to Django's /accounts/login/, which this project never
# wires up. The Wagtail admin keeps its own form as a fallback for local
# superusers; see semprini/templates/wagtailadmin/login.html.
LOGIN_URL = 'oidc_authentication_init'
LOGIN_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL_FAILURE = '/'
LOGOUT_REDIRECT_URL = '/'

# Lets a link name the identity provider to use, so the header's GitHub button
# skips Keycloak's own provider-picker page. Only aliases listed here are
# passed on; they must match the IdP aliases provisioned in semprini-core
# (core_stack/scripts/setup-keycloak-idp.py).
OIDC_AUTHENTICATE_CLASS = 'views.SempriniOIDCAuthenticationRequestView'
OIDC_IDP_HINTS = ('github',)

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-nz"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static_collected")
STATIC_URL = "/static/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Wagtail settings

WAGTAIL_SITE_NAME = "semprini"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "https://semprini.me"

PUPUT_AS_PLUGIN = True

# devcast page types extend puput's EntryPage so they inherit its dated URLs,
# feeds, archives and comment plumbing. This has to stay put: changing it after
# the first migration changes the table shape.
DEVCAST_PAGE_BASE = "puput.models.EntryPage"
DEVCAST_PUPUT_INTEGRATION = True
DEVCAST_BASE_TEMPLATE = "puput/base.html"

# Narration. Credentials are never listed here: the engine reads
# ELEVEN_LABS_API_KEY from the environment of the narrator container only.
# The budget is a guard against a runaway re-render, not a target.
DEVCAST_MONTHLY_CHAR_BUDGET = int(os.environ.get("DEVCAST_MONTHLY_CHAR_BUDGET", 250000))
DEVCAST_DEFAULT_VOICE = {
    "key": "semprini-v1",
    "label": "Semprini",
    "engine": "elevenlabs",
    "engine_voice_id": "ev2kMR9ZJZZsemuogS5u",
    "stability": 0.45,
    "similarity_boost": 0.8,
    "style": 0.15,
}

AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", None)
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "ap-southeast-2")
if AWS_STORAGE_BUCKET_NAME:

    def _s3(location):
        return {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": os.environ.get("AWS_ACCESS_KEY_ID", None),
                "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY", None),
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "location": location,
                "object_parameters": {"CacheControl": "max-age=86400"},
                "default_acl": "public-read",
                "file_overwrite": False,
                "region_name": AWS_S3_REGION_NAME,
                # Objects are public, so URLs must be plain and cacheable
                # rather than expiring signed ones, and must keep the exact
                # path shape that is already published across the site.
                "querystring_auth": False,
                "custom_domain": f"s3.{AWS_S3_REGION_NAME}.amazonaws.com/{AWS_STORAGE_BUCKET_NAME}",
            },
        }

    STORAGES = {"default": _s3("media")}

    # collectstatic runs during the image build, which has no credentials, so
    # static stays on the filesystem and is pushed by upload_static_s3.py
    # afterwards. Opt in only where that is not true.
    if os.environ.get("AWS_S3_STATICFILES"):
        STORAGES["staticfiles"] = _s3("static")
    else:
        STORAGES["staticfiles"] = {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
