# Generated by Django 6.0.2 on 2026-09-05 04:40

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puput', '0008_alter_tagentrypage_tag'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dev project index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DevProjectPage',
            fields=[
                ('entrypage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puput.entrypage')),
                ('tagline', models.CharField(blank=True, help_text='One line shown under the title and on cards.', max_length=200, verbose_name='tagline')),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('released', 'Released'), ('maintenance', 'Maintenance'), ('shelved', 'Shelved')], default='concept', max_length=20)),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='started')),
                ('repo_url', models.URLField(blank=True, verbose_name='source')),
                ('demo_url', models.URLField(blank=True, verbose_name='live demo')),
                ('download_url', models.URLField(blank=True, verbose_name='download')),
                ('showcase', wagtail.fields.StreamField([('heading', 2), ('text', 3), ('image', 7), ('gallery', 10), ('video', 13), ('code', 17), ('model3d', 20), ('callout', 22), ('quote', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section'), ('h3', 'Sub-section'), ('h4', 'Minor')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('devcast.blocks.ProseBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Spoken instead of the caption. Leave empty to skip this image in narration.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('narration', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (4,), {}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 5), ('narration', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': "Spoken lead-in. The video's own audio is never part of the narration.", 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('embed', 11), ('caption', 5), ('narration', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'text', 'max_length': 30, 'required': False}), 15: ('wagtail.blocks.TextBlock', (), {}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Describe what the code does. The code itself is never read aloud.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('language', 14), ('code', 15), ('narration', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'A .glb file.'}), 19: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('model', 18), ('caption', 5), ('autorotate', 19), ('narration', 9)]], {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('warning', 'Warning'), ('tip', 'Tip')]}), 22: ('wagtail.blocks.StructBlock', [[('style', 21), ('text', 15)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('quote', 15), ('attribution', 23)]], {})}, verbose_name='showcase')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_model', models.ForeignKey(blank=True, help_text='A .glb shown in place of the hero image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='hero 3D model')),
            ],
            options={
                'verbose_name': 'Dev project',
            },
            bases=('puput.entrypage',),
        ),
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('version', models.CharField(blank=True, help_text='Leave empty for changes that are not tied to a release.', max_length=40)),
                ('released_on', models.DateField(verbose_name='date')),
                ('kind', models.CharField(choices=[('added', 'Added'), ('changed', 'Changed'), ('fixed', 'Fixed'), ('removed', 'Removed'), ('note', 'Note')], default='changed', max_length=20)),
                ('summary', models.CharField(max_length=200)),
                ('detail', wagtailmarkdown.fields.MarkdownField(blank=True)),
                ('commit_url', models.URLField(blank=True, verbose_name='commit or PR')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='devcast.devprojectpage')),
            ],
            options={
                'verbose_name': 'change',
                'verbose_name_plural': 'changes',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='devcast.devprojectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text="Font Awesome name without the 'fa-' prefix, e.g. 'github'.", max_length=40)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='devcast.devprojectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_tags', to='devcast.devprojectpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='devprojectpage',
            name='stack',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='devcast.ProjectStackTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done'), ('dropped', 'Dropped')], default='planned', max_length=20)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='devcast.devprojectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
