# Generated by Django 6.0.2 on 2026-09-05 06:07

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcast', '0001_initial'),
        ('puput', '0008_alter_tagentrypage_tag'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEntryPage',
            fields=[
                ('entrypage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puput.entrypage')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('sections', wagtail.fields.StreamField([('heading', 2), ('text', 3), ('image', 7), ('gallery', 10), ('video', 13), ('code', 17), ('model3d', 20), ('callout', 22), ('quote', 24), ('aside', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section'), ('h3', 'Sub-section'), ('h4', 'Minor')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('devcast.blocks.ProseBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Spoken instead of the caption. Leave empty to skip this image in narration.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('narration', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (4,), {}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 5), ('narration', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': "Spoken lead-in. The video's own audio is never part of the narration.", 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('embed', 11), ('caption', 5), ('narration', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'text', 'max_length': 30, 'required': False}), 15: ('wagtail.blocks.TextBlock', (), {}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Describe what the code does. The code itself is never read aloud.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('language', 14), ('code', 15), ('narration', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'A .glb file.'}), 19: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('model', 18), ('caption', 5), ('autorotate', 19), ('narration', 9)]], {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('warning', 'Warning'), ('tip', 'Tip')]}), 22: ('wagtail.blocks.StructBlock', [[('style', 21), ('text', 15)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('quote', 15), ('attribution', 23)]], {}), 25: ('wagtail.blocks.StructBlock', [[('narration', 15)]], {})}, verbose_name='sections')),
                ('narration_enabled', models.BooleanField(default=True)),
                ('audio_duration', models.FloatField(blank=True, help_text='Used as the end of the final cue.', null=True, verbose_name='audio length (seconds)')),
                ('manual_audio', models.ForeignKey(blank=True, help_text='Uploaded audio. Generated narration replaces this later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='narration audio')),
            ],
            options={
                'verbose_name': 'Audio entry',
                'verbose_name_plural': 'Audio entries',
            },
            bases=('puput.entrypage',),
        ),
        migrations.CreateModel(
            name='AudioCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('start', models.FloatField(help_text='Cues bind to sections in order: the first cue times the first section.', verbose_name='starts at (seconds)')),
                ('note', models.CharField(blank=True, max_length=120)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='devcast.audioentrypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
