# Generated by Django 6.0.2 on 2026-09-06 01:24

import devcast.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcast', '0002_audioentrypage_audiocue'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_hash', models.CharField(db_index=True, max_length=64)),
                ('engine', models.CharField(max_length=32)),
                ('engine_rev', models.CharField(help_text='Model revision plus voice tuning fingerprint.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('audio', models.FileField(blank=True, upload_to=devcast.models.narration_path)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('cues', models.JSONField(blank=True, default=list)),
                ('words', models.JSONField(blank=True, default=list)),
                ('visemes', models.JSONField(blank=True, default=list)),
                ('char_count', models.IntegerField(default=0)),
                ('cost_cents', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrations', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'narration',
                'ordering': ['-created_at'],
                'permissions': [('render_narration', 'Can render narration')],
            },
        ),
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('leased_by', models.CharField(blank=True, max_length=120)),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='devcast.rendition')),
            ],
            options={
                'verbose_name': 'render job',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier used by --voice and in logs.', max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('engine', models.CharField(default='elevenlabs', max_length=32)),
                ('engine_voice_id', models.CharField(help_text="The provider's id for this voice.", max_length=64)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Engine tuning, e.g. stability and similarity_boost.')),
                ('is_default', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration_voices', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'voice',
            },
        ),
        migrations.AddField(
            model_name='rendition',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='devcast.voice'),
        ),
        migrations.AddConstraint(
            model_name='voice',
            constraint=models.UniqueConstraint(fields=('site', 'key'), name='devcast_voice_key'),
        ),
        migrations.AddConstraint(
            model_name='voice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('site',), name='devcast_one_default_voice_per_site'),
        ),
        migrations.AddConstraint(
            model_name='rendition',
            constraint=models.UniqueConstraint(fields=('page', 'voice', 'script_hash', 'engine_rev'), name='devcast_rendition_unique'),
        ),
    ]
