# Generated by Django 6.0.2 on 2026-09-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcast', '0003_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioentrypage',
            name='voice',
            field=models.ForeignKey(blank=True, help_text="Leave empty to use the site's default voice.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='devcast.voice', verbose_name='voice'),
        ),
    ]
