# Generated by Django 6.0.2 on 2026-09-06 09:25

import devcast.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def bill_existing_renditions(apps, schema_editor):
    """Everything recorded before clip reuse was bought in full, so the monthly
    budget must keep counting it."""
    Rendition = apps.get_model("devcast", "Rendition")
    Rendition.objects.update(billed_chars=F("char_count"))


class Migration(migrations.Migration):

    dependencies = [
        ('devcast', '0005_voice_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendition',
            name='billed_chars',
            field=models.IntegerField(default=0, help_text='Characters actually sent to the engine. Lower than the script length when unchanged sections were reused.'),
        ),
        migrations.CreateModel(
            name='SegmentClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_rev', models.CharField(max_length=64)),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('char_count', models.IntegerField(default=0)),
                ('audio', models.FileField(blank=True, upload_to=devcast.models.clip_path)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('words', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='devcast.voice')),
            ],
            options={
                'verbose_name': 'narration clip',
                'ordering': ['-last_used_at'],
                'constraints': [models.UniqueConstraint(fields=('voice', 'engine_rev', 'text_hash'), name='devcast_clip_unique')],
            },
        ),
        migrations.RunPython(bill_existing_renditions, migrations.RunPython.noop),
    ]
