# Generated by Django 6.0.2 on 2026-09-12 00:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcast', '0006_rendition_billed_chars_segmentclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('source', models.FileField(help_text='The .svg exported from draw.io.', upload_to='diagrams/', verbose_name='SVG export')),
                ('model_source', models.FileField(blank=True, help_text="Optional but worth adding: the model names the connectors, which the SVG cannot. Exporting with 'Include a copy of my diagram' does the same job.", upload_to='diagrams/', verbose_name='.drawio source')),
                ('page', models.CharField(blank=True, help_text='Which page of the .drawio this SVG came from.', max_length=120, verbose_name='page')),
                ('markup', models.TextField(blank=True, editable=False)),
                ('cell_index', models.JSONField(blank=True, default=list, editable=False)),
                ('script', models.JSONField(blank=True, default=dict, editable=False)),
                ('stats', models.JSONField(blank=True, default=dict, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'diagram',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='audioentrypage',
            name='sections',
            field=wagtail.fields.StreamField([('heading', 2), ('text', 3), ('image', 7), ('gallery', 10), ('video', 13), ('code', 17), ('model3d', 20), ('diagram', 23), ('callout', 25), ('quote', 27), ('aside', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section'), ('h3', 'Sub-section'), ('h4', 'Minor')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('devcast.blocks.ProseBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Spoken instead of the caption. Leave empty to skip this image in narration.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('narration', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (4,), {}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 5), ('narration', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': "Spoken lead-in. The video's own audio is never part of the narration.", 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('embed', 11), ('caption', 5), ('narration', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'text', 'max_length': 30, 'required': False}), 15: ('wagtail.blocks.TextBlock', (), {}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Describe what the code does. The code itself is never read aloud.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('language', 14), ('code', 15), ('narration', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'A .glb file.'}), 19: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('model', 18), ('caption', 5), ('autorotate', 19), ('narration', 9)]], {}), 21: ('wagtail.snippets.blocks.SnippetChooserBlock', ('devcast.Diagram',), {}), 22: ('wagtail.blocks.TextBlock', (), {'help_text': 'Spoken while the diagram plays. Leave empty to skip it in narration.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('diagram', 21), ('caption', 5), ('narration', 22)]], {}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('warning', 'Warning'), ('tip', 'Tip')]}), 25: ('wagtail.blocks.StructBlock', [[('style', 24), ('text', 15)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('quote', 15), ('attribution', 26)]], {}), 28: ('wagtail.blocks.StructBlock', [[('narration', 15)]], {})}, verbose_name='sections'),
        ),
        migrations.AlterField(
            model_name='devprojectpage',
            name='showcase',
            field=wagtail.fields.StreamField([('heading', 2), ('text', 3), ('image', 7), ('gallery', 10), ('video', 13), ('code', 17), ('model3d', 20), ('diagram', 23), ('callout', 25), ('quote', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section'), ('h3', 'Sub-section'), ('h4', 'Minor')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('devcast.blocks.ProseBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Spoken instead of the caption. Leave empty to skip this image in narration.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('narration', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (4,), {}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 5), ('narration', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': "Spoken lead-in. The video's own audio is never part of the narration.", 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('embed', 11), ('caption', 5), ('narration', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'text', 'max_length': 30, 'required': False}), 15: ('wagtail.blocks.TextBlock', (), {}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Describe what the code does. The code itself is never read aloud.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('language', 14), ('code', 15), ('narration', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'A .glb file.'}), 19: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('model', 18), ('caption', 5), ('autorotate', 19), ('narration', 9)]], {}), 21: ('wagtail.snippets.blocks.SnippetChooserBlock', ('devcast.Diagram',), {}), 22: ('wagtail.blocks.TextBlock', (), {'help_text': 'Spoken while the diagram plays. Leave empty to skip it in narration.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('diagram', 21), ('caption', 5), ('narration', 22)]], {}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('warning', 'Warning'), ('tip', 'Tip')]}), 25: ('wagtail.blocks.StructBlock', [[('style', 24), ('text', 15)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('quote', 15), ('attribution', 26)]], {})}, verbose_name='showcase'),
        ),
    ]
