# Generated by Django 6.0.2 on 2026-09-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcast', '0007_diagram_alter_audioentrypage_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='script',
            field=models.JSONField(blank=True, default=dict, help_text='Optional. Leave empty for a still diagram. Targets are the keys listed under Targets below.', verbose_name='animation script'),
        ),
    ]
